### ISSUE TITLE
Pretty __repr__

### ISSUE THREAD

**Issue by vreuter** [pepkit/attmap#22]
Render nice YAML or JSON from `attmap` data

- [x] hook for inclusion of most specific type name
~~- [ ] format arg (e.g., YAML or JSON)~~
- [x] implement/check `__str__` and look for `mark.xfail`s

**Comment by nsheff** [comment]
I think you're probably already solved this, but I just realized you could potentially use `yaml.dump` to render the attmap object as yaml... though this would introduce that dependency on `pyyaml`.

just wanted to add it as a thought, if we did go that route for other reasons, it might be more robust to edge cases than rolling our own (?)
