### ISSUE TITLE
easy loading from yaml file?

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#27]
what do you think of adding a function like this:

```
def load_yaml(filename):
  with open(filename) as file:
    return yaml.safe_load(file)
 ```

ultimately this would help to make it easier to load a yaml file... it would be nice to do something like:

```
import attmap
x = attmap.AttMap("config.yaml")
```

**Comment by nsheff** [comment]
or if not directyl in the constructor, which could be reserved for dict-like data, then:

```
x= attmap.load_yaml("config.yaml", class=PathExAttMap)
```

or something.

**Comment by vreuter** [comment]
Currently there are no dependencies. I don't think it makes sense to add one for this. Besides further biasing the library toward YAML (over, e.g., JSON, which has support in the standard library), this saves just two lines (an `import yaml` statement and reducing the object creation from 2 lines to 1)

**Comment by nsheff** [comment]
yeah I see. that's fine. I just find myself doing this over and over again, in interactive sessions and in every pepkit package that uses attmap, so I thought it might make sense to standardize. any other way you see to simplify this need? maybe add to ubiquerg?

**Comment by vreuter** [comment]
Right now `ubiquerg` has the same dependency-free status (I think). I think it'd make a ton of sense to add to out most generic package that does already use `PyYAML` + `attmap`, though.

**Comment by nsheff** [comment]
alright sounds great. I'll keep that in mind. thanks.

**Comment by nsheff** [comment]
what immediately comes to mind is: peppy, divvy, and the new refgenie class I'm working on... but these lack a common progenitor unfortunately. oh well.

**Comment by vreuter** [comment]
We almost need a `pepkit`-specific utils; :thinking: ...do we have enough stuff that'd belong there to warrant it? Is that even much a threshold? We could maybe use `divvy` in the meantime...

**Comment by nsheff** [comment]
peppy has a method called `to_yaml` on `Sample` objects:

https://github.com/pepkit/peppy/blob/d2c23497077809b25cd37d70cbf2d4f25e4aca25/peppy/sample.py#L826

this would also fit into this category. 

There needs to be an attmap+pyyaml package to hold all of this stuff. Maybe this is a new package called `yamlattmap` or just `yattmap` for short. are you sure this isn't fundamental enough to include the base attmap package? I'm still undecided.

**Comment by nsheff** [comment]
put another way: I think the ability to go seamlessly to and from files and attmap objects seems pretty fundamental, and supporting both JSON and YAML seems pretty widely useful.

**Comment by nsheff** [comment]
@afrendeiro you wrote the `to_yaml` function -- can you chime in with any ideas here.

Also, can you explain what to_yaml is doing that is beyond the basic  `dump` functionality of [pyyaml](https://pyyaml.org/wiki/PyYAMLDocumentation) ? It looks like a lot of extra logic you're doing  -- what did `dump` not work for?

**Comment by vreuter** [comment]
> peppy has a method called `to_yaml` on `Sample` objects:
> 
> https://github.com/pepkit/peppy/blob/d2c23497077809b25cd37d70cbf2d4f25e4aca25/peppy/sample.py#L826
> 
> this would also fit into this category.
> 
> There needs to be an attmap+pyyaml package to hold all of this stuff. Maybe this is a new package called `yamlattmap` or just `yattmap` for short. are you sure this isn't fundamental enough to include the base attmap package? I'm still undecided.

Yeah; we use it a lot, but YAML is an atypical dependency. INI and JSON have broader use, I'd guess.
