### ISSUE TITLE
MutableMapping vs Dict

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#30]
Right now, attmap objects are inheriting from `MutableMapping`. Why does attmap not extend `Dict` instead? 

I'm sure there's some reason I don't see.

The reason I ask is that the `__dict__` function is not recursing across attmap objects. See what I mean:

```
In [43]: a = attmap.AttMap({'a':1, 'b':2, 'c': {'c1': 500, 'c2': 750}})                                 

In [47]: type(a)                                                                                        
Out[47]: attmap.attmap.AttMap

In [48]: type(a.c)                                                                                      
Out[48]: attmap.attmap.AttMap

In [51]: type(a.__dict__)                                                                               
Out[51]: dict

In [49]: a.__dict__["c"]                                                                                
Out[49]: {'c2': 750, 'c1': 500}

In [50]: type(a.__dict__["c"])                                                                          
Out[50]: attmap.attmap.AttMap
```

would it be simple to make a function that converts the attmap to a dict recursively? I think this may also simplify the `obj2dict` function by @afrendeiro:

https://github.com/pepkit/peppy/blob/d2c23497077809b25cd37d70cbf2d4f25e4aca25/peppy/sample.py#L863-L905

**Comment by vreuter** [comment]
https://github.com/pepkit/attmap/blob/master/attmap/_att_map_like.py#L153

**Comment by vreuter** [comment]
> https://github.com/pepkit/attmap/blob/master/attmap/_att_map_like.py#L153

Sorry, not exactly a helpful docstring on `master`, esp the `return` tag :man_facepalming:

**Comment by nsheff** [comment]
I still don't understand... sorry...

**Comment by vreuter** [comment]
I don't understand the question...there's `to_map` for conversion
