### ISSUE TITLE
OrdPathExAttMap

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#33]
AttributeError: 'module' object has no attribute 'PathExAttMap'

was it intentional to break backwards compatibility with the 0.8 update, and going forward is it to be `OrdPathExAttMap` only,  with no `PathExAttMap` ?

are any current tools using attmap that will now be broken with this release to pypi?

**Comment by vreuter** [comment]
Yep! Doubt we have too many attmap users outside of pepkit so far who’d be upgrading attmap independently of a pepkit project

**Comment by vreuter** [comment]
All projects should now be updated on respective `dev` branches; sorry, perhaps I should've done the round-robin of updates before releasing 0.8. Please reopen if one or more dependents was missed, thouugh.

**Comment by nsheff** [comment]
Ok are you sure no pepkit projects are using it though? Because if so, they would be currently broken, right?

FWIW I think we should simplify the naming a bit... I'd favor just sticking with PathExAttMap and making them ordered. I can't think of a scenario where keeping things ordered will cause a major problem so I don't think that needs to be reflected in the name... thoughts?

**Comment by nsheff** [comment]
our comments crossed, sorry -- I typed that out but didn't submit it until after yours.

I see you updated divvy, etc. on dev -- but current *release* versions of those will be currently non-functional, correct?

like if I right now `pip install divvy` I'll get a broken `divvy`, right? So we need to go re-release everything now again, right?

**Comment by vreuter** [comment]
I think you should decide a name and we should use that, and proceed accordingly with release or nonrelease of new versions of dependentss.

**Comment by nsheff** [comment]
I find it confusing that there's `OrdPathExAttMap` without `PathExAttMap`. So, I think one of the following two alternatives should happen, and I'll let you decide which you like better:

solution 1: We use `OrdPathExAttMap`, but put `PathExAttMap` back for an unordered one.
solution 2: We only offer `PathExAttMap`, which is ordered, because we think there's no reason to want an unordered one.

The only solution I don't understand is offering only 1 of them, and naming it `OrdPathExAttMap`. I have a slight preference for solution 2 but can ago either way. what do you think?

Also I think from here on out it looks like attmap is being used enough (if only by us) that it's worth preserving backwards-compatibility as much as we can easily do...

**Comment by vreuter** [comment]
> I see you updated divvy, etc. on dev -- but current _release_ versions of those will be currently non-functional, correct?
> 
> like if I right now `pip install divvy` I'll get a broken `divvy`, right? So we need to go re-release everything now again, right?

I see what you mean; yes, that's right. I think your solution 2 makes most sense, though. I don't know about the internals, but it seems plausible that the only disadvantages to the ordering are speed and perhaps serialization difficulty depending on the use case / library that wants serialized data. 
Speed should be a pretty negligible issue since what seems like typical motivation for wanting attribute-style access is more intimate domain knowledge of the map's data (and therefore likely fewer keys), and the `to_map` function should help mitigate the cost of complicating serialization.

So I vote for your sol'n 2. Furthermore, in that case there won't be new releases for the dependents.

**Comment by nsheff** [comment]
Ok, thanks, I agree! that sounds perfect.

So `OrdAttMap` is *ordered* but *not path expanding*, right? This is the case we need for `refgenconf` (since we'll be taking round-trips to/from disk). I think this will be a fairly common use case.

**Comment by vreuter** [comment]
> So `OrdAttMap` is _ordered_ but _not path expanding_, right? 

Correct.
