### ISSUE TITLE
Deferred path expansion

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#37]
What about having a `PathExAttmap` expand paths upon attribute access, rather than on loading? That would enable it to be serialized to/from disk without loss.

it would also enable this type of access:

```
pam = PathExAttmap(...)
pam.myvar = $VARIABLE
pam.myvar
> $VARIABLE
```

**Comment by vreuter** [comment]
Yeah good idea; the additional benefit is that you could likely dynamically change the expansion by modifying `os.environ`

**Comment by nsheff** [comment]
> eah good idea; the additional benefit is that you could likely dynamically change the expansion by modifying `os.environ`

exactly...
