### ISSUE TITLE
class hierarchy docs and naming convention ideas

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#38]
it would be nice to add to the docs something like this to codify the inheritance of the maps:

```
- AttMap
  - OrdAttMap
    - PathExAttMap
      - AttMapEcho
```

At some point we may have multiple subclasses under one of them, and this would accommodate that nicely.

Also, I was wondering what you think about making a naming convention, which is: all subclasses of Attmap are named in the same way, which is: **ModifierAttMap**, where *Modifier* is the *lowest attribute in the class hierarchy* above. This will avoid some of the confusion that we were facing with `OrdPathExAttMap`, which can get even hairy with 4-5 levels down (like EchoOrdPathExAttMap), etc. So we'd just say an "EchoAttMap" would fit this standard.

Our classes would be: `AttMap`,  `OrdAttMap`, `PathExAttMap`, `EchoAttMap` at the moment. I'm working on another that will be:

```
class YacAttMap(attmap.OrdAttMap):
```

provided by yacman, which will add the yaml reading/writing stuff.

**Comment by vreuter** [comment]
Whenever you're comfortable with me completely removing `AttMapEcho`, I'm all in.

**Comment by nsheff** [comment]
can we: 

1. Add `EchoAttMap`  and start using it
2. Alias AttMapEcho until we're ready to do the next round of updates on all the tools currently depending on AttMapEcho
3. Remove AttMapEcho after those are released.

?

this seems like the most prudent approach.

**Comment by vreuter** [comment]
What's the upside to adding `EchoAttMap` and _deliberately introducing_ the need for dual naming, rather than naming it `AttMapEcho` wherever you want to use it anew, and then doing all the changes in one sweep?

**Comment by nsheff** [comment]
that I don't have to do all the work of changes in one sweep.  development cycle continues normally.

really, to me, this seems like the only way to do it. I can't comprehend the approach of going through the effort to re-release all downstream stuff immediately.... it just doesn't make sense to me to do all that extra work. it's so much easier to just release 1 version of attmap that has 2 ways to do it, and then remove after the normal release cycles of all other software are complete...

**Comment by nsheff** [comment]
thank you!
