### ISSUE TITLE
Printing contents without class name

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#40]
Related to #8 

what is your recommended way to print the item without the name (like, so I can get just the yaml in yacman). the way I did this now is by overriding the __repr__ with:

```
    def __repr__(self):
        data = self._simplify_keyvalue(self._data_for_repr())
        if data:
            return "\n".join(
                attmap.get_data_lines(data, lambda obj: repr(obj).strip("'")))
        else:
            return "{}"
```

do you suggest something else?

**Comment by nsheff** [comment]
if this is a good solution, can we add a `get_data_repr` function to `AttMap` and then call it from the default `__repr__`, so a user could use: `AttMap.data_repr()` or something if they wanted just the raw data? This is what I will use to serialize the yaml in yacman.

**Comment by vreuter** [comment]
It doesn't matter at all to me. Can you open tickets with exactly what you want for:
- [ ] `repr`
- [ ] `serialization`
They're different and should be treated as such.

**Comment by nsheff** [comment]
can we talk about this one briefly? It will help me understand what serialization is and get us on the same page

**Comment by vreuter** [comment]
https://github.com/pepkit/attmap/commit/530d0c8dea296d6f96d0b3d056a87e381ee24b86

**Comment by nsheff** [comment]
this worked beautifully for me, thanks.
