### ISSUE TITLE
what's the difference between to_map and to_dict?

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#45]
on `PathExAttMap`, what's the difference between to_map and to_dict?

http://attmap.databio.org/en/latest/autodoc_build/attmap/

can you add to docstring?

**Comment by nsheff** [comment]
`to_dict` goes all the way to `dict`, while `to_map` only converts into the 'lower bound' object?

**Comment by vreuter** [comment]
Yep you got it
