### ISSUE TITLE
links don't point to api anchors

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#58]
https://attmap.databio.org/en/latest/types/'

the links are to in-document anchors but they don't work.

**Comment by nsheff** [comment]
I think this is related to: https://github.com/pepkit/peppy/issues/311

**Comment by vreuter** [comment]
Yeah, I pushed the commit with the attempted links as a first-attempt without them being functional yet, thinking with your Markdown / general docs expertise you may already have a good solution. I searched around for a bit when I was writing that little types snippet, but I couldn't find anything that fully worked.
