### ISSUE TITLE
doubleslashes

### ISSUE THREAD

**Issue by nsheff** [pepkit/attmap#64]
a pathexattmap will apparently turn any double-slashes into single-slashes, even for things that aren't paths.

**Comment by nsheff** [comment]
Related to #46

I think the attmap should not touch double-slashes at all... or only fix them in a simple string that's clearly a path, with no spaces, etc.

**Comment by nsheff** [comment]
This is biting me again in bulker.

**Comment by vreuter** [comment]
An issue is that in Python 2 there was no great way (that I know of) to give a string path semantics. I think with 3.5+ you can use `path.py`, though.

**Comment by nsheff** [comment]
luckily, python 2 is dying soon :)

**Comment by nsheff** [comment]
I believe this issue was solved in ubiquerg upstream
